FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
COPY backend/package*.json ./backend/
RUN npm install

# Copy source code
COPY backend ./backend
COPY tsconfig.json ./

# Build backend
RUN npm run build -w backend

# Expose port
EXPOSE 3001

# Start server
CMD ["npm", "start", "-w", "backend"]
