services:
  - type: web
    name: memora-app
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
